cmake_minimum_required(VERSION 3.6)

project(OpenOMF)

find_library(SDL2_mixer SDL2_mixer)
find_library(SDL2 SDL2)

add_library(main SHARED)

file(GLOB CONFUSE_SRC
        "deps/libconfuse/src/*.c")
file(GLOB ENET_SRC
        "deps/enet/*.c")
file(GLOB EPOXY_SRC
        "deps/libepoxy/src/*.c")
set(PNG_SRC
        deps/libpng-code/example.c
        deps/libpng-code/png.c
        deps/libpng-code/pngerror.c
        deps/libpng-code/pngget.c
        deps/libpng-code/pngmem.c
        deps/libpng-code/pngpread.c
        deps/libpng-code/pngread.c
        deps/libpng-code/pngrio.c
        deps/libpng-code/pngrtran.c
        deps/libpng-code/pngrutil.c
        deps/libpng-code/pngset.c
        deps/libpng-code/pngtrans.c
        deps/libpng-code/pngwio.c
        deps/libpng-code/pngwrite.c
        deps/libpng-code/pngwtran.c
        deps/libpng-code/pngwutil.c

        deps/libpng-code/arm/arm_init.c
        deps/libpng-code/arm/filter_neon_intrinsics.c
        deps/libpng-code/arm/palette_neon_intrinsics.c)
set(XMP_SRC
        deps/libxmp/src/control.c
        deps/libxmp/src/dataio.c
        deps/libxmp/src/effects.c
        deps/libxmp/src/extras.c
        deps/libxmp/src/far_extras.c
        deps/libxmp/src/filetype.c
        deps/libxmp/src/filter.c
        deps/libxmp/src/flow.c
        deps/libxmp/src/flt_extras.c
        deps/libxmp/src/format.c
        deps/libxmp/src/hio.c
        deps/libxmp/src/hmn_extras.c
        deps/libxmp/src/lfo.c
        deps/libxmp/src/load.c
        deps/libxmp/src/load_helpers.c
        deps/libxmp/src/md5.c
        deps/libxmp/src/med_extras.c
        deps/libxmp/src/memio.c
        deps/libxmp/src/miniz_tinfl.c
        deps/libxmp/src/misc.c
        deps/libxmp/src/mix_all.c
        deps/libxmp/src/mixer.c
        deps/libxmp/src/mix_paula.c
        deps/libxmp/src/mkstemp.c
        deps/libxmp/src/path.c
        deps/libxmp/src/period.c
        deps/libxmp/src/player.c
        deps/libxmp/src/read_event.c
        deps/libxmp/src/rng.c
        deps/libxmp/src/scan.c
        deps/libxmp/src/smix.c
        deps/libxmp/src/tempfile.c
        deps/libxmp/src/virtual.c

        deps/libxmp/src/loaders/669_load.c
        deps/libxmp/src/loaders/abk_load.c
        deps/libxmp/src/loaders/amf_load.c
        deps/libxmp/src/loaders/arch_load.c
        deps/libxmp/src/loaders/asylum_load.c
        deps/libxmp/src/loaders/chip_load.c
        deps/libxmp/src/loaders/coco_load.c
        deps/libxmp/src/loaders/common.c
        deps/libxmp/src/loaders/dbm_load.c
        deps/libxmp/src/loaders/digi_load.c
        deps/libxmp/src/loaders/dt_load.c
        deps/libxmp/src/loaders/emod_load.c
        deps/libxmp/src/loaders/far_load.c
        deps/libxmp/src/loaders/flt_load.c
        deps/libxmp/src/loaders/fnk_load.c
        deps/libxmp/src/loaders/gal4_load.c
        deps/libxmp/src/loaders/gal5_load.c
        deps/libxmp/src/loaders/gdm_load.c
        deps/libxmp/src/loaders/hmn_load.c
        deps/libxmp/src/loaders/ice_load.c
        deps/libxmp/src/loaders/iff.c
        deps/libxmp/src/loaders/imf_load.c
        deps/libxmp/src/loaders/ims_load.c
        deps/libxmp/src/loaders/it_load.c
        deps/libxmp/src/loaders/itsex.c
        deps/libxmp/src/loaders/liq_load.c
        deps/libxmp/src/loaders/lzw.c
        deps/libxmp/src/loaders/masi16_load.c
        deps/libxmp/src/loaders/masi_load.c
        deps/libxmp/src/loaders/mdl_load.c
        deps/libxmp/src/loaders/med2_load.c
        deps/libxmp/src/loaders/med3_load.c
        deps/libxmp/src/loaders/med4_load.c
        deps/libxmp/src/loaders/mfp_load.c
        deps/libxmp/src/loaders/mgt_load.c
        deps/libxmp/src/loaders/mmd1_load.c
        deps/libxmp/src/loaders/mmd3_load.c
        deps/libxmp/src/loaders/mmd_common.c
        deps/libxmp/src/loaders/mod_load.c
        deps/libxmp/src/loaders/mtm_load.c
        deps/libxmp/src/loaders/muse_load.c
        deps/libxmp/src/loaders/no_load.c
        deps/libxmp/src/loaders/okt_load.c
        deps/libxmp/src/loaders/pt3_load.c
        deps/libxmp/src/loaders/ptm_load.c
        deps/libxmp/src/loaders/pw_load.c
        deps/libxmp/src/loaders/rtm_load.c
        deps/libxmp/src/loaders/s3m_load.c
        deps/libxmp/src/loaders/sample.c
        deps/libxmp/src/loaders/sfx_load.c
        deps/libxmp/src/loaders/stim_load.c
        deps/libxmp/src/loaders/st_load.c
        deps/libxmp/src/loaders/stm_load.c
        deps/libxmp/src/loaders/stx_load.c
        deps/libxmp/src/loaders/sym_load.c
        deps/libxmp/src/loaders/ult_load.c
        deps/libxmp/src/loaders/umx_load.c
        deps/libxmp/src/loaders/voltable.c
        deps/libxmp/src/loaders/vorbis.c
        deps/libxmp/src/loaders/xmf_load.c
        deps/libxmp/src/loaders/xm_load.c

        deps/libxmp/src/depackers/arc.c
        deps/libxmp/src/depackers/arcfs.c
        deps/libxmp/src/depackers/arc_unpack.c
        deps/libxmp/src/depackers/bunzip2.c
        deps/libxmp/src/depackers/crc32.c
        deps/libxmp/src/depackers/depacker.c
        deps/libxmp/src/depackers/gunzip.c
        deps/libxmp/src/depackers/ice.c
        deps/libxmp/src/depackers/ice_unpack.c
        deps/libxmp/src/depackers/lzx.c
        deps/libxmp/src/depackers/lzx_unpack.c
        deps/libxmp/src/depackers/miniz_zip.c
        deps/libxmp/src/depackers/mmcmp.c
        deps/libxmp/src/depackers/ppdepack.c
        deps/libxmp/src/depackers/ptpopen.c
        deps/libxmp/src/depackers/s404_dec.c
        deps/libxmp/src/depackers/uncompress.c
        deps/libxmp/src/depackers/unlha.c
        deps/libxmp/src/depackers/unsqsh.c
        deps/libxmp/src/depackers/unxz.c
        deps/libxmp/src/depackers/unzip.c
        deps/libxmp/src/depackers/xfd.c
        deps/libxmp/src/depackers/xfd_link.c
        deps/libxmp/src/depackers/xfnmatch.c
        deps/libxmp/src/depackers/xz_dec_lzma2.c
        deps/libxmp/src/depackers/xz_dec_stream.c

        deps/libxmp/src/loaders/prowizard/ac1d.c
        deps/libxmp/src/loaders/prowizard/di.c
        deps/libxmp/src/loaders/prowizard/eureka.c
        deps/libxmp/src/loaders/prowizard/fc-m.c
        deps/libxmp/src/loaders/prowizard/fuchs.c
        deps/libxmp/src/loaders/prowizard/fuzzac.c
        deps/libxmp/src/loaders/prowizard/gmc.c
        deps/libxmp/src/loaders/prowizard/heatseek.c
        deps/libxmp/src/loaders/prowizard/hrt.c
        deps/libxmp/src/loaders/prowizard/ksm.c
        deps/libxmp/src/loaders/prowizard/mp.c
        deps/libxmp/src/loaders/prowizard/noiserun.c
        deps/libxmp/src/loaders/prowizard/novotrade.c
        deps/libxmp/src/loaders/prowizard/np1.c
        deps/libxmp/src/loaders/prowizard/np2.c
        deps/libxmp/src/loaders/prowizard/np3.c
        deps/libxmp/src/loaders/prowizard/p40.c
        deps/libxmp/src/loaders/prowizard/p61a.c
        deps/libxmp/src/loaders/prowizard/pha.c
        deps/libxmp/src/loaders/prowizard/pm10c.c
        deps/libxmp/src/loaders/prowizard/pm18a.c
        deps/libxmp/src/loaders/prowizard/pp10.c
        deps/libxmp/src/loaders/prowizard/pp21.c
        deps/libxmp/src/loaders/prowizard/prowiz.c
        deps/libxmp/src/loaders/prowizard/prun1.c
        deps/libxmp/src/loaders/prowizard/prun2.c
        deps/libxmp/src/loaders/prowizard/ptktable.c
        deps/libxmp/src/loaders/prowizard/skyt.c
        deps/libxmp/src/loaders/prowizard/starpack.c
        deps/libxmp/src/loaders/prowizard/tdd.c
        deps/libxmp/src/loaders/prowizard/theplayer.c
        deps/libxmp/src/loaders/prowizard/titanics.c
        deps/libxmp/src/loaders/prowizard/tp1.c
        deps/libxmp/src/loaders/prowizard/tp3.c
        deps/libxmp/src/loaders/prowizard/tuning.c
        deps/libxmp/src/loaders/prowizard/unic2.c
        deps/libxmp/src/loaders/prowizard/unic.c
        deps/libxmp/src/loaders/prowizard/wn.c
        deps/libxmp/src/loaders/prowizard/xann.c
        deps/libxmp/src/loaders/prowizard/zen.c

        deps/libxmp/src/depackers/lhasa/ext_header.c
        deps/libxmp/src/depackers/lhasa/lh1_decoder.c
        deps/libxmp/src/depackers/lhasa/lh5_decoder.c
        deps/libxmp/src/depackers/lhasa/lh6_decoder.c
        deps/libxmp/src/depackers/lhasa/lh7_decoder.c
        deps/libxmp/src/depackers/lhasa/lha_basic_reader.c
        deps/libxmp/src/depackers/lhasa/lha_decoder.c
        deps/libxmp/src/depackers/lhasa/lha_file_header.c
        deps/libxmp/src/depackers/lhasa/lha_input_stream.c
        deps/libxmp/src/depackers/lhasa/lha_reader.c
        deps/libxmp/src/depackers/lhasa/lh_new_decoder.c
        deps/libxmp/src/depackers/lhasa/lhx_decoder.c
        deps/libxmp/src/depackers/lhasa/lk7_decoder.c
        deps/libxmp/src/depackers/lhasa/lz5_decoder.c
        deps/libxmp/src/depackers/lhasa/lzs_decoder.c
        deps/libxmp/src/depackers/lhasa/macbinary.c
        deps/libxmp/src/depackers/lhasa/null_decoder.c
        deps/libxmp/src/depackers/lhasa/pm1_decoder.c
        deps/libxmp/src/depackers/lhasa/pm2_decoder.c
)

set(OPENOMF_SRC
        video/damage_tracker.c
        video/image.c
        video/vga_palette.c
        video/vga_state.c
        video/vga_remap.c
        video/video.c
        video/surface.c
        video/renderers/common.c
        video/renderers/opengl3/gl3_renderer.c
        video/renderers/opengl3/helpers/palette.c
        video/renderers/opengl3/helpers/render_target.c
        video/renderers/opengl3/helpers/vao.c
        video/renderers/opengl3/helpers/vbo.c
        video/renderers/opengl3/helpers/shaders.c
        video/renderers/opengl3/helpers/fbo.c
        video/renderers/opengl3/helpers/object_array.c
        video/renderers/opengl3/helpers/bindings.c
        video/renderers/opengl3/helpers/remaps.c
        video/renderers/opengl3/helpers/texture_atlas.c
        video/renderers/opengl3/helpers/texture.c
        video/renderers/opengl3/sdl_window.c
        video/renderers/null/null_renderer.c
        engine.c
        formats/animation.c
        formats/move.c
        formats/sprite.c
        formats/palette.c
        formats/setup.c
        formats/tag_list_helpers.c
        formats/chr.c
        formats/sounds.c
        formats/vga_image.c
        formats/rgba_image.c
        formats/script_reader.c
        formats/fonts.c
        formats/pcx.c
        formats/script.c
        formats/pic.c
        formats/error.c
        formats/rec_assertion.c
        formats/tag_list.c
        formats/pilot.c
        formats/bkanim.c
        formats/tournament.c
        formats/af.c
        formats/score.c
        formats/altpal.c
        formats/bk.c
        formats/rec.c
        formats/language.c
        formats/internal/writer.c
        formats/internal/memwriter.c
        formats/internal/memreader.c
        formats/internal/reader.c
        vendored/zip/zip.c
        vendored/argtable/argtable3.c
        main.c
        game/common_defines.c
        game/scenes/mainmenu.c
        game/scenes/melee.c
        game/scenes/newsroom.c
        game/scenes/credits.c
        game/scenes/vs.c
        game/scenes/openomf.c
        game/scenes/cutscene.c
        game/scenes/mainmenu/menu_advanced.c
        game/scenes/mainmenu/menu_language.c
        game/scenes/mainmenu/menu_audio.c
        game/scenes/mainmenu/menu_listen.c
        game/scenes/mainmenu/menu_keyboard.c
        game/scenes/mainmenu/menu_net.c
        game/scenes/mainmenu/menu_presskey.c
        game/scenes/mainmenu/menu_video.c
        game/scenes/mainmenu/menu_connect.c
        game/scenes/mainmenu/menu_configuration.c
        game/scenes/mainmenu/menu_help.c
        game/scenes/mainmenu/menu_netconfig.c
        game/scenes/mainmenu/menu_input.c
        game/scenes/mainmenu/menu_main.c
        game/scenes/mainmenu/menu_video_confirm.c
        game/scenes/mainmenu/menu_gameplay.c
        game/scenes/arena.c
        game/scenes/intro.c
        game/scenes/mechlab/lab_menu_confirm.c
        game/scenes/mechlab/lab_menu_difficultyselect.c
        game/scenes/mechlab/button_details.c
        game/scenes/mechlab/lab_menu_select.c
        game/scenes/mechlab/lab_dash_newplayer.c
        game/scenes/mechlab/lab_menu_trade.c
        game/scenes/mechlab/har_economy.c
        game/scenes/mechlab/lab_menu_main.c
        game/scenes/mechlab/lab_menu_customize.c
        game/scenes/mechlab/lab_dash_main.c
        game/scenes/mechlab/lab_dash_trnselect.c
        game/scenes/mechlab/lab_menu_training.c
        game/scenes/lobby.c
        game/scenes/mechlab.c
        game/scenes/scoreboard.c
        game/game_player.c
        game/audio/sound_tracker.c
        game/audio/music_tracker.c
        game/audio/audio_sources.c
        game/objects/hazard.c
        game/objects/har.c
        game/objects/scrap.c
        game/objects/projectile.c
        game/game_state.c
        game/protos/player.c
        game/protos/intersect.c
        game/protos/scene.c
        game/protos/object.c
        game/gui/menu_background.c
        game/gui/component.c
        game/gui/textinput.c
        game/gui/xysizer.c
        game/gui/trnselect.c
        game/gui/trn_menu.c
        game/gui/label.c
        game/gui/textselector.c
        game/gui/osd/osd.c
        game/gui/gauge.c
        game/gui/widget.c
        game/gui/button.c
        game/gui/menu.c
        game/gui/sizer.c
        game/gui/filler.c
        game/gui/portrait.c
        game/gui/gui_frame.c
        game/gui/dialog.c
        game/gui/spriteimage.c
        game/gui/spritebutton.c
        game/gui/text/text_layout.c
        game/gui/text/text.c
        game/gui/textslider.c
        game/gui/progressbar.c
        game/utils/settings.c
        game/utils/ticktimer.c
        game/utils/version.c
        game/utils/formatting.c
        game/utils/har_screencap.c
        game/utils/score.c
        game/utils/nat.c
        game/utils/serial.c
        audio/music_sources/psm_source.c
        audio/music_sources/opus_source.c
        audio/music_sources/null_music_source.c
        audio/sound_sources/null_sound_source.c
        audio/sound_sources/dat_source.c
        audio/audio.c
        audio/backends/sdl/sdl_backend.c
        audio/backends/null/null_backend.c
        resources/script_cache.c
        resources/animation.c
        resources/sprite.c
        resources/pilots.c
        resources/bk_loader.c
        resources/af_loader.c
        resources/fonts.c
        resources/languages.c
        resources/ids.c
        resources/modmanager.c
        resources/trnmanager.c
        resources/af.c
        resources/bk_info.c
        resources/sgmanager.c
        resources/af_move.c
        resources/resource_paths.c
        resources/bk.c
        resources/sounds_loader.c
        resources/resource_files.c
        resources/scores.c
        console/console.c
        console/console_cmd.c
        controller/rec_controller.c
        controller/ai_controller.c
        controller/spec_controller.c
        controller/controller.c
        controller/joystick.c
        controller/keyboard.c
        controller/net_controller.c
        controller/game_controller_db.c
        utils/time_fmt.c
        utils/c_string_util.c
        utils/sprite_packer.c
        utils/config.c
        utils/array.c
        utils/vector.c
        utils/cp437.c
        utils/png_reader.c
        utils/random.c
        utils/msgbox.c
        utils/crash.c
        utils/hashmap.c
        utils/log.c
        utils/str.c
        utils/list.c
        utils/ringbuffer.c
        utils/iterator.c
        utils/png_writer.c
        utils/path.c
        utils/smallbuffer.c
        utils/sstream.c
)

file(GLOB OGG_SRC
        deps/SDL2_mixer-2.8.2/external/ogg/src/*.c)
set(OPUS_SRC
        deps/SDL2_mixer-2.8.2/external/opus/src/analysis.c
        deps/SDL2_mixer-2.8.2/external/opus/src/mapping_matrix.c
        deps/SDL2_mixer-2.8.2/external/opus/src/mlp.c
        deps/SDL2_mixer-2.8.2/external/opus/src/mlp_data.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_decoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_encoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_multistream.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_multistream_decoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_multistream_encoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_projection_decoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/opus_projection_encoder.c
        deps/SDL2_mixer-2.8.2/external/opus/src/repacketizer.c
)
set(OPUSCELT_SRC
        deps/SDL2_mixer-2.8.2/external/opus/celt/bands.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/celt.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/celt_decoder.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/celt_encoder.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/celt_lpc.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/cwrs.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/entcode.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/entdec.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/entenc.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/kiss_fft.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/laplace.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/mathops.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/mdct.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/modes.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/pitch.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/quant_bands.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/rate.c
        deps/SDL2_mixer-2.8.2/external/opus/celt/vq.c
)
file(GLOB OPUSSILK_SRC
        deps/SDL2_mixer-2.8.2/external/opus/silk/*.c)
file(GLOB OPUSSILKFLOAT_SRC
        deps/SDL2_mixer-2.8.2/external/opus/silk/float/*.c)
file(GLOB OPUSFILE_SRC
        deps/SDL2_mixer-2.8.2/external/opusfile/src/*.c)
file(GLOB ZLIB_SRC
        deps/zlib-1.3.2/*.c)

target_sources(main PRIVATE
        ${CONFUSE_SRC}
        ${ENET_SRC}
        ${EPOXY_SRC}
        ${OGG_SRC}
        ${OPENOMF_SRC}
        ${OPUS_SRC}
        ${OPUSCELT_SRC}
        ${OPUSSILK_SRC}
        ${OPUSSILKFLOAT_SRC}
        ${OPUSFILE_SRC}
        ${PNG_SRC}
        ${XMP_SRC}
        ${ZLIB_SRC}
)
target_compile_definitions(main PRIVATE
        V_MAJOR=0
        V_MINOR=8
        V_PATCH=6
        EPOXY_EGL=1
        ENABLE_OPENGL3_RENDERER
        ENABLE_SDL_AUDIO_BACKEND
        HAS_SOCKLEN_T
        HAVE_FUNOPEN
        HAVE_STRDUP
        HAVE_STRNDUP
        HISTORY_BITS=5
        NUM_CODES=512
        OFFSET_BITS=16
        PACKAGE_STRING="Android"
        PACKAGE_VERSION="Android"
        PNG_FOUND
        STREAMSIZE=1024
        OPUS_BUILD
        OPUSFILE_FOUND
        VAR_ARRAYS
)
target_include_directories(main PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}
        deps/libconfuse/src
        deps/enet/include
        deps/libpng-code
        deps/libepoxy/include
        deps/libepoxy/src
        deps/libxmp/include
        deps/libxmp/src/depackers/lhasa
        deps/SDL2_mixer-2.8.2/external/ogg/include
        deps/SDL2_mixer-2.8.2/external/opus/include
        deps/SDL2_mixer-2.8.2/external/opus/celt
        deps/SDL2_mixer-2.8.2/external/opus/silk
        deps/SDL2_mixer-2.8.2/external/opus/silk/float
        deps/SDL2_mixer-2.8.2/external/opusfile/include
        vendored/argtable
)
target_link_libraries(main SDL2_mixer SDL2 GLESv3 log)